### ISSUE TITLE
Agregar Barra de Estado a las Fichas

### ISSUE THREAD

**Issue by CiarlantiniD** [HopscotchWebStudio/Faun#2]
Especificar el comportamiento de la barra de estado de la ficha para la mascota.

**Comment by gusrabun** [comment]
Es por tiempo de publicación. Es decir si se reporta una mascota determinado día, la barra avanza 30 días calendario. Una vez que vence vuelve a contactar al usuario y le repregunta si quiere seguir con la publicación, o la quiere dar de baja. sino contesta se da de baja automaticamente.
